spring:
  # Test Database Configuration with H2 in-memory
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  # JPA Configuration for Tests
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false

  # Completely disable Redis for tests
  data:
    redis:
      repositories:
        enabled: false
      # Disable Redis auto-configuration completely
      host: 
      port: 
      timeout: 
      url: 
  
  # Disable Redis session for tests
  session:
    store-type: none
    redis:
      flush-mode: on_save
      namespace: 
      cleanup-cron: 

  # Completely disable Spring Cloud Gateway for tests
  cloud:
    gateway:
      enabled: false
    discovery:
      enabled: false

  # Disable Liquibase for tests - use JPA DDL auto-generation instead
  liquibase:
    enabled: false

  # Disable all Redis auto-configuration
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

# Disable Eureka for tests
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

# Test-specific logging
logging:
  level:
    com.carddemo: DEBUG
    org.springframework.test: INFO
    org.hibernate.SQL: INFO
    liquibase: INFO