# Spring Cloud Configuration for CardDemo Development Environment
# Replaces CICS SIT parameters with cloud-native configuration

spring:
  application:
    name: carddemo
  profiles:
    active: development
    
  # Database configuration
  datasource:
    url: jdbc:postgresql://postgresql-service:5432/carddemo
    username: carddemo_dev
    password: dev_password_123
    driver-class-name: org.postgresql.Driver
    
    # HikariCP connection pool settings
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  # Redis configuration
  data:
    redis:
      host: redis-service
      port: 6379
      database: 0
      timeout: 2s
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2

  # Session management
  session:
    store-type: redis
    redis:
      namespace: "carddemo:session"
    timeout: 30m

# Security configuration
carddemo:
  jwt:
    secret: dev-secret-key-for-local-development-only-change-in-production
    expiration: 3600
  security:
    cors:
      allowed-origins: "http://localhost:3000,http://localhost:8080"

# Logging configuration
logging:
  level:
    com.carddemo: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
