# PostgreSQL Database Credentials Secret
# This secret contains the PostgreSQL database authentication credentials
# for the CardDemo application's migrated VSAM data storage layer.
#
# Purpose:
# - Provides secure credential storage for PostgreSQL database access
# - Separates database authentication from application configuration
# - Enables secure credential management for the modernized Spring Boot architecture
#
# Referenced by:
# - PostgreSQL StatefulSet for database initialization and authentication
# - Backend application Secret for JDBC connection string construction
# - Spring Boot service configuration for database connection pool setup
#
# Migration Context:
# This replaces the mainframe VSAM dataset access credentials with
# cloud-native PostgreSQL authentication supporting the technology
# stack transformation documented in Section 8.4.3.

apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: default
  labels:
    app: carddemo
    component: database
    tier: data
    environment: production
  annotations:
    description: "PostgreSQL database credentials for CardDemo application"
    migration.carddemo.com/legacy-system: "VSAM-KSDS-datasets"
    migration.carddemo.com/modernized-component: "PostgreSQL-relational-database"
    security.carddemo.com/credential-type: "database-authentication"
type: Opaque
data:
  # PostgreSQL username: carddemo_user
  # Base64 encoded value for database authentication
  username: Y2FyZGRlbW9fdXNlcg==
  
  # PostgreSQL password: CardDemo2024!
  # Base64 encoded secure password for database access
  # Note: In production, this should be replaced with a more secure,
  # randomly generated password and managed through proper secret management
  password: Q2FyZERlbW8yMDI0IQ==

---
# PostgreSQL Admin Secret (optional)
# Separate admin credentials for database administration tasks
# This provides additional security isolation between application
# access and administrative operations
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-admin-secret
  namespace: default
  labels:
    app: carddemo
    component: database
    tier: data
    environment: production
    access-level: admin
  annotations:
    description: "PostgreSQL admin credentials for database administration"
    migration.carddemo.com/purpose: "database-administration"
    security.carddemo.com/credential-type: "database-admin"
type: Opaque
data:
  # PostgreSQL admin username: carddemo_admin
  # Base64 encoded value for administrative operations
  username: Y2FyZGRlbW9fYWRtaW4=
  
  # PostgreSQL admin password: CardDemoAdmin2024!
  # Base64 encoded admin password for privileged operations
  password: Q2FyZERlbW9BZG1pbjIwMjQh